In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

In [2]:
PROJECT_ROOT = Path("/home/harielpadillasanchez/Documentos/TT/TT2")

ZERO_DIR = PROJECT_ROOT / "outputs" / "ruleset_comparison_zero"
OUT_DIR = PROJECT_ROOT / "outputs" / "comparison_finalists_zero"
OUT_DIR.mkdir(parents=True, exist_ok=True)

ZERO_FILE = ZERO_DIR / "exp_ruleset_comparison_zero_20260502_235933_summary_by_ruleset.csv"

print("ZERO_FILE:", ZERO_FILE)
print("OUT_DIR:", OUT_DIR)
print("Existe ZERO_FILE:", ZERO_FILE.exists())

ZERO_FILE: /home/harielpadillasanchez/Documentos/TT/TT2/outputs/ruleset_comparison_zero/exp_ruleset_comparison_zero_20260502_235933_summary_by_ruleset.csv
OUT_DIR: /home/harielpadillasanchez/Documentos/TT/TT2/outputs/comparison_finalists_zero
Existe ZERO_FILE: True

In [3]:
df_all = pd.read_csv(ZERO_FILE)

print("Shape cargado:", df_all.shape)
display(df_all.head(3))
display(df_all.columns.tolist())

Shape cargado: (50, 29)

,owner,model_key,config_label,ruleset,gen_temperature,gen_top_p,gen_repetition_penalty,gen_max_new_tokens,gen_do_sample,gen_no_repeat_ngram_size,...,additions_proportion,deletions_proportion,rouge1_f,rouge2_f,rougeL_f,inflesz_pred,inflesz_src,inflesz_delta,bertscore_f1,leader_score
0,hariel,llama3,hariel_llama3_cfg_1,R0,0.2,0.85,1.05,256,NaN,NaN,...,0.335613,0.509976,0.483206,0.288552,0.405020,73.239084,51.983615,21.255469,0.802757,57.300870
1,hariel,llama3,hariel_llama3_cfg_1,R1,0.2,0.85,1.05,256,NaN,NaN,...,0.431450,0.502076,0.447493,0.252202,0.394901,68.925717,51.983615,16.942102,0.797565,56.459191
2,hariel,llama3,hariel_llama3_cfg_1,R2,0.2,0.85,1.05,256,NaN,NaN,...,0.395192,0.557373,0.444645,0.230932,0.376377,75.044209,51.983615,23.060594,0.794482,55.232725

['owner',
 'model_key',
 'config_label',
 'ruleset',
 'gen_temperature',
 'gen_top_p',
 'gen_repetition_penalty',
 'gen_max_new_tokens',
 'gen_do_sample',
 'gen_no_repeat_ngram_size',
 'sari',
 'bleu',
 'fernandez_huerta_pred',
 'fernandez_huerta_src',
 'fernandez_huerta_delta',
 'compression_ratio_eval',
 'sentence_splits',
 'levenshtein_similarity',
 'exact_copy',
 'additions_proportion',
 'deletions_proportion',
 'rouge1_f',
 'rouge2_f',
 'rougeL_f',
 'inflesz_pred',
 'inflesz_src',
 'inflesz_delta',
 'bertscore_f1',
 'leader_score']

In [4]:
if "owner" not in df_all.columns:
    df_all["owner"] = "unknown"

print("Owners detectados:", df_all["owner"].dropna().unique().tolist())
print("Modelos detectados:", df_all["model_key"].dropna().unique().tolist())

Owners detectados: ['hariel', 'nancy']
Modelos detectados: ['llama3', 'mistral']

In [5]:
optional_cols = [
    "gen_temperature",
    "gen_top_p",
    "gen_repetition_penalty",
    "gen_max_new_tokens",
    "gen_do_sample",
    "gen_no_repeat_ngram_size",
]

for col in optional_cols:
    if col not in df_all.columns:
        df_all[col] = np.nan

df_all["gen_do_sample"] = df_all["gen_do_sample"].astype("string").fillna("NA")
df_all["gen_no_repeat_ngram_size"] = df_all["gen_no_repeat_ngram_size"].astype("string").fillna("NA")

print("Columnas normalizadas.")

Columnas normalizadas.

In [6]:
group_cols_preview = [
    c for c in [
        "owner",
        "model_key",
        "config_label",
        "ruleset",
        "gen_temperature",
        "gen_top_p",
        "gen_repetition_penalty",
        "gen_max_new_tokens",
        "gen_do_sample",
        "gen_no_repeat_ngram_size",
        "sari",
        "bertscore_f1",
        "rougeL_f",
        "compression_ratio_eval",
        "exact_copy",
    ]
    if c in df_all.columns
]

display(df_all[group_cols_preview].head(10))

,owner,model_key,config_label,ruleset,gen_temperature,gen_top_p,gen_repetition_penalty,gen_max_new_tokens,gen_do_sample,gen_no_repeat_ngram_size,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy
0,hariel,llama3,hariel_llama3_cfg_1,R0,0.2,0.85,1.05,256,NA,NA,41.984327,0.802757,0.405020,0.746944,0.0
1,hariel,llama3,hariel_llama3_cfg_1,R1,0.2,0.85,1.05,256,NA,NA,40.927673,0.797565,0.394901,0.889054,0.0
2,hariel,llama3,hariel_llama3_cfg_1,R2,0.2,0.85,1.05,256,NA,NA,39.089079,0.794482,0.376377,0.734288,0.0
3,hariel,llama3,hariel_llama3_cfg_1,R3,0.2,0.85,1.05,256,NA,NA,39.830596,0.803366,0.392203,0.769154,0.0
4,hariel,llama3,hariel_llama3_cfg_1,R4,0.2,0.85,1.05,256,NA,NA,40.174015,0.795653,0.384787,0.764278,0.0
5,hariel,llama3,hariel_llama3_cfg_2,R0,0.2,0.90,1.10,256,NA,NA,40.016114,0.796184,0.377270,0.791278,0.0
6,hariel,llama3,hariel_llama3_cfg_2,R1,0.2,0.90,1.10,256,NA,NA,38.195938,0.788665,0.359976,0.758187,0.0
7,hariel,llama3,hariel_llama3_cfg_2,R2,0.2,0.90,1.10,256,NA,NA,39.577409,0.790770,0.374492,0.783359,0.0
8,hariel,llama3,hariel_llama3_cfg_2,R3,0.2,0.90,1.10,256,NA,NA,38.463321,0.790559,0.355399,0.790301,0.0
9,hariel,llama3,hariel_llama3_cfg_2,R4,0.2,0.90,1.10,256,NA,NA,39.663867,0.789294,0.374822,0.792923,0.0

In [7]:
df_rank = df_all.copy()

if "exact_copy" in df_rank.columns:
    df_rank = df_rank[df_rank["exact_copy"] < 0.50].copy()

if "compression_ratio_eval" in df_rank.columns:
    df_rank = df_rank[
        (df_rank["compression_ratio_eval"] > 0.60) &
        (df_rank["compression_ratio_eval"] < 1.60)
    ].copy()

df_rank["leader_score"] = (
    0.6 * df_rank["sari"] +
    0.4 * (df_rank["bertscore_f1"] * 100.0)
)

print("Shape después de filtros:", df_rank.shape)

display(
    df_rank[
        [c for c in [
            "owner", "model_key", "config_label", "ruleset",
            "sari", "bertscore_f1", "leader_score",
            "compression_ratio_eval", "exact_copy"
        ] if c in df_rank.columns]
    ].head(10)
)

Shape después de filtros: (50, 29)

,owner,model_key,config_label,ruleset,sari,bertscore_f1,leader_score,compression_ratio_eval,exact_copy
0,hariel,llama3,hariel_llama3_cfg_1,R0,41.984327,0.802757,57.300870,0.746944,0.0
1,hariel,llama3,hariel_llama3_cfg_1,R1,40.927673,0.797565,56.459191,0.889054,0.0
2,hariel,llama3,hariel_llama3_cfg_1,R2,39.089079,0.794482,55.232725,0.734288,0.0
3,hariel,llama3,hariel_llama3_cfg_1,R3,39.830596,0.803366,56.032999,0.769154,0.0
4,hariel,llama3,hariel_llama3_cfg_1,R4,40.174015,0.795653,55.930532,0.764278,0.0
5,hariel,llama3,hariel_llama3_cfg_2,R0,40.016114,0.796184,55.857018,0.791278,0.0
6,hariel,llama3,hariel_llama3_cfg_2,R1,38.195938,0.788665,54.464174,0.758187,0.0
7,hariel,llama3,hariel_llama3_cfg_2,R2,39.577409,0.790770,55.377231,0.783359,0.0
8,hariel,llama3,hariel_llama3_cfg_2,R3,38.463321,0.790559,54.700367,0.790301,0.0
9,hariel,llama3,hariel_llama3_cfg_2,R4,39.663867,0.789294,55.370086,0.792923,0.0

In [8]:
def safe_str(v):
    if pd.isna(v):
        return "NA"
    return str(v)

df_rank["config_signature"] = df_rank.apply(
    lambda r: " | ".join([
        safe_str(r.get("owner")),
        safe_str(r.get("model_key")),
        safe_str(r.get("config_label")),
        safe_str(r.get("ruleset")),
        f"temp={safe_str(r.get('gen_temperature'))}",
        f"top_p={safe_str(r.get('gen_top_p'))}",
        f"rep={safe_str(r.get('gen_repetition_penalty'))}",
        f"max_new={safe_str(r.get('gen_max_new_tokens'))}",
        f"do_sample={safe_str(r.get('gen_do_sample'))}",
        f"ngram={safe_str(r.get('gen_no_repeat_ngram_size'))}",
    ]),
    axis=1
)

display(df_rank[["config_signature"]].head(5))

                                    config_signature
0  hariel | llama3 | hariel_llama3_cfg_1 | R0 | t...
1  hariel | llama3 | hariel_llama3_cfg_1 | R1 | t...
2  hariel | llama3 | hariel_llama3_cfg_1 | R2 | t...
3  hariel | llama3 | hariel_llama3_cfg_1 | R3 | t...
4  hariel | llama3 | hariel_llama3_cfg_1 | R4 | t...

In [9]:
ranking_global_zero = df_rank.sort_values(
    by=["leader_score", "sari", "bertscore_f1"],
    ascending=False
).reset_index(drop=True)

display(
    ranking_global_zero[
        [c for c in [
            "owner",
            "model_key",
            "config_label",
            "ruleset",
            "gen_temperature",
            "gen_top_p",
            "gen_repetition_penalty",
            "gen_max_new_tokens",
            "gen_do_sample",
            "gen_no_repeat_ngram_size",
            "sari",
            "bertscore_f1",
            "rougeL_f",
            "compression_ratio_eval",
            "exact_copy",
            "leader_score",
        ] if c in ranking_global_zero.columns]
    ].head(20)
)

ranking_global_zero.to_csv(OUT_DIR / "ranking_global_zero.csv", index=False, encoding="utf-8-sig")
print(OUT_DIR / "ranking_global_zero.csv")

,owner,model_key,config_label,ruleset,gen_temperature,gen_top_p,gen_repetition_penalty,gen_max_new_tokens,gen_do_sample,gen_no_repeat_ngram_size,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy,leader_score
0,hariel,llama3,hariel_llama3_cfg_1,R0,0.2,0.85,1.05,256,NA,NA,41.984327,0.802757,0.405020,0.746944,0.0,57.300870
1,nancy,mistral,nancy_mistral_cfg_2,R4,0.3,0.90,1.15,400,True,4.0,41.904275,0.801483,0.396466,0.902308,0.0,57.201885
2,hariel,mistral,hariel_mistral_cfg_1,R4,0.3,0.90,1.10,256,NA,NA,41.313539,0.799005,0.383889,1.010825,0.0,56.748324
3,hariel,llama3,hariel_llama3_cfg_1,R1,0.2,0.85,1.05,256,NA,NA,40.927673,0.797565,0.394901,0.889054,0.0,56.459191
4,hariel,mistral,hariel_mistral_cfg_3,R1,0.2,0.85,1.10,256,NA,NA,40.852745,0.798477,0.413970,1.047526,0.0,56.450713
5,nancy,mistral,nancy_mistral_cfg_1,R0,0.7,0.90,1.10,512,True,4.0,40.336949,0.802013,0.408220,0.972621,0.0,56.282678
6,hariel,mistral,hariel_mistral_cfg_3,R0,0.2,0.85,1.10,256,NA,NA,40.552833,0.797208,0.408561,0.972869,0.0,56.220031
7,hariel,mistral,hariel_mistral_cfg_2,R1,0.1,0.85,1.10,256,NA,NA,40.565152,0.796415,0.403377,1.110639,0.0,56.195683
8,hariel,llama3,hariel_llama3_cfg_3,R4,0.3,0.90,1.15,256,NA,NA,40.659859,0.792474,0.365241,0.843799,0.0,56.094857
9,hariel,llama3,hariel_llama3_cfg_1,R3,0.2,0.85,1.05,256,NA,NA,39.830596,0.803366,0.392203,0.769154,0.0,56.032999
10,hariel,mistral,hariel_mistral_cfg_3,R4,0.2,0.85,1.10,256,NA,NA,41.107321,0.783069,0.358385,1.148421,0.0,55.987142
11,hariel,llama3,hariel_llama3_cfg_1,R4,0.2,0.85,1.05,256,NA,NA,40.174015,0.795653,0.384787,0.764278,0.0,55.930532
12,hariel,llama3,hariel_llama3_cfg_2,R0,0.2,0.90,1.10,256,NA,NA,40.016114,0.796184,0.377270,0.791278,0.0,55.857018
13,hariel,mistral,hariel_mistral_cfg_1,R3,0.3,0.90,1.10,256,NA,NA,40.399084,0.789529,0.372958,1.004110,0.0,55.820593
14,nancy,llama3,nancy_llama3_cfg_2,R2,0.7,0.90,1.10,512,True,4.0,40.348848,0.788883,0.349668,0.807471,0.0,55.764627
15,hariel,mistral,hariel_mistral_cfg_2,R4,0.1,0.85,1.10,256,NA,NA,40.345765,0.787863,0.356916,1.209809,0.0,55.721960
16,nancy,mistral,nancy_mistral_cfg_2,R0,0.3,0.90,1.15,400,True,4.0,39.777972,0.796144,0.399967,1.019297,0.0,55.712558
17,hariel,mistral,hariel_mistral_cfg_1,R1,0.3,0.90,1.10,256,NA,NA,39.811073,0.795443,0.394730,1.131808,0.0,55.704373
18,hariel,mistral,hariel_mistral_cfg_2,R2,0.1,0.85,1.10,256,NA,NA,40.089808,0.790187,0.385374,1.148215,0.0,55.661375
19,nancy,mistral,nancy_mistral_cfg_1,R3,0.7,0.90,1.10,512,True,4.0,40.738447,0.776105,0.368792,1.290190,0.0,55.487282

/home/harielpadillasanchez/Documentos/TT/TT2/outputs/comparison_finalists_zero/ranking_global_zero.csv

In [10]:
top5_by_model_zero = (
    df_rank
    .sort_values(
        by=["model_key", "leader_score", "sari", "bertscore_f1"],
        ascending=[True, False, False, False]
    )
    .groupby("model_key", as_index=False, group_keys=False)
    .head(5)
    .reset_index(drop=True)
)

display(
    top5_by_model_zero[
        [c for c in [
            "owner",
            "model_key",
            "config_label",
            "ruleset",
            "gen_temperature",
            "gen_top_p",
            "gen_repetition_penalty",
            "gen_max_new_tokens",
            "gen_do_sample",
            "gen_no_repeat_ngram_size",
            "sari",
            "bertscore_f1",
            "leader_score",
        ] if c in top5_by_model_zero.columns]
    ]
)

top5_by_model_zero.to_csv(OUT_DIR / "top5_by_model_zero.csv", index=False, encoding="utf-8-sig")
print(OUT_DIR / "top5_by_model_zero.csv")

,owner,model_key,config_label,ruleset,gen_temperature,gen_top_p,gen_repetition_penalty,gen_max_new_tokens,gen_do_sample,gen_no_repeat_ngram_size,sari,bertscore_f1,leader_score
0,hariel,llama3,hariel_llama3_cfg_1,R0,0.2,0.85,1.05,256,NA,NA,41.984327,0.802757,57.300870
1,hariel,llama3,hariel_llama3_cfg_1,R1,0.2,0.85,1.05,256,NA,NA,40.927673,0.797565,56.459191
2,hariel,llama3,hariel_llama3_cfg_3,R4,0.3,0.90,1.15,256,NA,NA,40.659859,0.792474,56.094857
3,hariel,llama3,hariel_llama3_cfg_1,R3,0.2,0.85,1.05,256,NA,NA,39.830596,0.803366,56.032999
4,hariel,llama3,hariel_llama3_cfg_1,R4,0.2,0.85,1.05,256,NA,NA,40.174015,0.795653,55.930532
5,nancy,mistral,nancy_mistral_cfg_2,R4,0.3,0.90,1.15,400,True,4.0,41.904275,0.801483,57.201885
6,hariel,mistral,hariel_mistral_cfg_1,R4,0.3,0.90,1.10,256,NA,NA,41.313539,0.799005,56.748324
7,hariel,mistral,hariel_mistral_cfg_3,R1,0.2,0.85,1.10,256,NA,NA,40.852745,0.798477,56.450713
8,nancy,mistral,nancy_mistral_cfg_1,R0,0.7,0.90,1.10,512,True,4.0,40.336949,0.802013,56.282678
9,hariel,mistral,hariel_mistral_cfg_3,R0,0.2,0.85,1.10,256,NA,NA,40.552833,0.797208,56.220031

/home/harielpadillasanchez/Documentos/TT/TT2/outputs/comparison_finalists_zero/top5_by_model_zero.csv

In [11]:
top5_by_owner_zero = (
    df_rank
    .sort_values(
        by=["owner", "leader_score", "sari", "bertscore_f1"],
        ascending=[True, False, False, False]
    )
    .groupby("owner", as_index=False, group_keys=False)
    .head(5)
    .reset_index(drop=True)
)

display(
    top5_by_owner_zero[
        [c for c in [
            "owner",
            "model_key",
            "config_label",
            "ruleset",
            "gen_temperature",
            "gen_top_p",
            "gen_repetition_penalty",
            "gen_max_new_tokens",
            "gen_do_sample",
            "gen_no_repeat_ngram_size",
            "sari",
            "bertscore_f1",
            "leader_score",
        ] if c in top5_by_owner_zero.columns]
    ]
)

top5_by_owner_zero.to_csv(OUT_DIR / "top5_by_owner_zero.csv", index=False, encoding="utf-8-sig")
print(OUT_DIR / "top5_by_owner_zero.csv")

,owner,model_key,config_label,ruleset,gen_temperature,gen_top_p,gen_repetition_penalty,gen_max_new_tokens,gen_do_sample,gen_no_repeat_ngram_size,sari,bertscore_f1,leader_score
0,hariel,llama3,hariel_llama3_cfg_1,R0,0.2,0.85,1.05,256,NA,NA,41.984327,0.802757,57.300870
1,hariel,mistral,hariel_mistral_cfg_1,R4,0.3,0.90,1.10,256,NA,NA,41.313539,0.799005,56.748324
2,hariel,llama3,hariel_llama3_cfg_1,R1,0.2,0.85,1.05,256,NA,NA,40.927673,0.797565,56.459191
3,hariel,mistral,hariel_mistral_cfg_3,R1,0.2,0.85,1.10,256,NA,NA,40.852745,0.798477,56.450713
4,hariel,mistral,hariel_mistral_cfg_3,R0,0.2,0.85,1.10,256,NA,NA,40.552833,0.797208,56.220031
5,nancy,mistral,nancy_mistral_cfg_2,R4,0.3,0.90,1.15,400,True,4.0,41.904275,0.801483,57.201885
6,nancy,mistral,nancy_mistral_cfg_1,R0,0.7,0.90,1.10,512,True,4.0,40.336949,0.802013,56.282678
7,nancy,llama3,nancy_llama3_cfg_2,R2,0.7,0.90,1.10,512,True,4.0,40.348848,0.788883,55.764627
8,nancy,mistral,nancy_mistral_cfg_2,R0,0.3,0.90,1.15,400,True,4.0,39.777972,0.796144,55.712558
9,nancy,mistral,nancy_mistral_cfg_1,R3,0.7,0.90,1.10,512,True,4.0,40.738447,0.776105,55.487282

/home/harielpadillasanchez/Documentos/TT/TT2/outputs/comparison_finalists_zero/top5_by_owner_zero.csv

In [12]:
top3_by_model_owner_zero = (
    df_rank
    .sort_values(
        by=["owner", "model_key", "leader_score", "sari", "bertscore_f1"],
        ascending=[True, True, False, False, False]
    )
    .groupby(["owner", "model_key"], as_index=False, group_keys=False)
    .head(3)
    .reset_index(drop=True)
)

display(
    top3_by_model_owner_zero[
        [c for c in [
            "owner",
            "model_key",
            "config_label",
            "ruleset",
            "gen_temperature",
            "gen_top_p",
            "gen_repetition_penalty",
            "gen_max_new_tokens",
            "gen_do_sample",
            "gen_no_repeat_ngram_size",
            "sari",
            "bertscore_f1",
            "leader_score",
        ] if c in top3_by_model_owner_zero.columns]
    ]
)

top3_by_model_owner_zero.to_csv(OUT_DIR / "top3_by_model_owner_zero.csv", index=False, encoding="utf-8-sig")
print(OUT_DIR / "top3_by_model_owner_zero.csv")

,owner,model_key,config_label,ruleset,gen_temperature,gen_top_p,gen_repetition_penalty,gen_max_new_tokens,gen_do_sample,gen_no_repeat_ngram_size,sari,bertscore_f1,leader_score
0,hariel,llama3,hariel_llama3_cfg_1,R0,0.2,0.85,1.05,256,NA,NA,41.984327,0.802757,57.300870
1,hariel,llama3,hariel_llama3_cfg_1,R1,0.2,0.85,1.05,256,NA,NA,40.927673,0.797565,56.459191
2,hariel,llama3,hariel_llama3_cfg_3,R4,0.3,0.90,1.15,256,NA,NA,40.659859,0.792474,56.094857
3,hariel,mistral,hariel_mistral_cfg_1,R4,0.3,0.90,1.10,256,NA,NA,41.313539,0.799005,56.748324
4,hariel,mistral,hariel_mistral_cfg_3,R1,0.2,0.85,1.10,256,NA,NA,40.852745,0.798477,56.450713
5,hariel,mistral,hariel_mistral_cfg_3,R0,0.2,0.85,1.10,256,NA,NA,40.552833,0.797208,56.220031
6,nancy,llama3,nancy_llama3_cfg_2,R2,0.7,0.90,1.10,512,True,4.0,40.348848,0.788883,55.764627
7,nancy,llama3,nancy_llama3_cfg_2,R1,0.7,0.90,1.10,512,True,4.0,38.929764,0.797807,55.270123
8,nancy,llama3,nancy_llama3_cfg_1,R3,0.3,0.90,1.15,256,True,4.0,38.966325,0.787269,54.870557
9,nancy,mistral,nancy_mistral_cfg_2,R4,0.3,0.90,1.15,400,True,4.0,41.904275,0.801483,57.201885
10,nancy,mistral,nancy_mistral_cfg_1,R0,0.7,0.90,1.10,512,True,4.0,40.336949,0.802013,56.282678
11,nancy,mistral,nancy_mistral_cfg_2,R0,0.3,0.90,1.15,400,True,4.0,39.777972,0.796144,55.712558

/home/harielpadillasanchez/Documentos/TT/TT2/outputs/comparison_finalists_zero/top3_by_model_owner_zero.csv

In [13]:
print("Resumen rapido zero")
print("-" * 50)
print("Total configs comparadas:", len(df_rank))
print("Owners:", df_rank["owner"].unique().tolist())
print("Modelos:", df_rank["model_key"].unique().tolist())

best_global = ranking_global_zero.iloc[0]

print("\nMejor config global zero:")
for col in [
    "owner",
    "model_key",
    "config_label",
    "ruleset",
    "gen_temperature",
    "gen_top_p",
    "gen_repetition_penalty",
    "gen_max_new_tokens",
    "gen_do_sample",
    "gen_no_repeat_ngram_size",
    "sari",
    "bertscore_f1",
    "leader_score",
]:
    if col in best_global.index:
        print(f"{col}: {best_global[col]}")

Resumen rapido zero
--------------------------------------------------
Total configs comparadas: 50
Owners: ['hariel', 'nancy']
Modelos: ['llama3', 'mistral']

Mejor config global zero:
owner: hariel
model_key: llama3
config_label: hariel_llama3_cfg_1
ruleset: R0
gen_temperature: 0.2
gen_top_p: 0.85
gen_repetition_penalty: 1.05
gen_max_new_tokens: 256
gen_do_sample: NA
gen_no_repeat_ngram_size: NA
sari: 41.98432695449868
bertscore_f1: 0.8027568548917771
leader_score: 57.30087036837028

In [14]:
top2_per_prompt_zero = (
    ranking_global_zero
    .groupby("model_key", as_index=False, group_keys=False)
    .head(2)
    .reset_index(drop=True)
)

display(
    top2_per_prompt_zero[
        [c for c in [
            "owner",
            "model_key",
            "config_label",
            "ruleset",
            "gen_temperature",
            "gen_top_p",
            "gen_repetition_penalty",
            "gen_max_new_tokens",
            "gen_do_sample",
            "gen_no_repeat_ngram_size",
            "sari",
            "bertscore_f1",
            "leader_score",
        ] if c in top2_per_prompt_zero.columns]
    ]
)

top2_per_prompt_zero.to_csv(OUT_DIR / "top2_per_model_zero.csv", index=False, encoding="utf-8-sig")
print(OUT_DIR / "top2_per_model_zero.csv")

,owner,model_key,config_label,ruleset,gen_temperature,gen_top_p,gen_repetition_penalty,gen_max_new_tokens,gen_do_sample,gen_no_repeat_ngram_size,sari,bertscore_f1,leader_score
0,hariel,llama3,hariel_llama3_cfg_1,R0,0.2,0.85,1.05,256,NA,NA,41.984327,0.802757,57.300870
1,nancy,mistral,nancy_mistral_cfg_2,R4,0.3,0.90,1.15,400,True,4.0,41.904275,0.801483,57.201885
2,hariel,mistral,hariel_mistral_cfg_1,R4,0.3,0.90,1.10,256,NA,NA,41.313539,0.799005,56.748324
3,hariel,llama3,hariel_llama3_cfg_1,R1,0.2,0.85,1.05,256,NA,NA,40.927673,0.797565,56.459191

/home/harielpadillasanchez/Documentos/TT/TT2/outputs/comparison_finalists_zero/top2_per_model_zero.csv