In [1]:
from pathlib import Path
import pandas as pd

In [7]:
PROJECT_ROOT = Path("/home/harielpadillasanchez/Documentos/TT/TT2")

# muestra final de 36
SAMPLE36_IDS_CSV = PROJECT_ROOT / "outputs" / "final_sample_36" / "feina_repr30_test_sample36_representative_ids.csv"

# prompting ya corrido
PROMPTING_SIMPLIFIED_CSV = PROJECT_ROOT / "outputs" / "prompting_on_sample36" / "exp_prompting_sample36_top4_20260505_022729_simplified_texts_only.csv"

# LoRA
LORA_LLAMA_EVAL_CSV = PROJECT_ROOT / "outputs" / "lora_runs" / "lora_llama3_feina_repr30_v1" / "evaluation" / "lora_test_evaluated.csv"
LORA_MISTRAL_EVAL_CSV = PROJECT_ROOT / "outputs" / "lora_runs" / "lora_mistral_feina_repr30_v1" / "evaluation" / "lora_test_evaluated.csv"

# carpeta final bien visible en raiz
FINAL_DIR = PROJECT_ROOT / "FINAL_COMPARACION_36"
FINAL_DIR.mkdir(parents=True, exist_ok=True)

print("SAMPLE36_IDS_CSV:", SAMPLE36_IDS_CSV, SAMPLE36_IDS_CSV.exists())
print("PROMPTING_SIMPLIFIED_CSV:", PROMPTING_SIMPLIFIED_CSV, PROMPTING_SIMPLIFIED_CSV.exists())
print("LORA_LLAMA_EVAL_CSV:", LORA_LLAMA_EVAL_CSV, LORA_LLAMA_EVAL_CSV.exists())
print("LORA_MISTRAL_EVAL_CSV:", LORA_MISTRAL_EVAL_CSV, LORA_MISTRAL_EVAL_CSV.exists())
print("FINAL_DIR:", FINAL_DIR)

SAMPLE36_IDS_CSV: /home/harielpadillasanchez/Documentos/TT/TT2/outputs/final_sample_36/feina_repr30_test_sample36_representative_ids.csv True
PROMPTING_SIMPLIFIED_CSV: /home/harielpadillasanchez/Documentos/TT/TT2/outputs/prompting_on_sample36/exp_prompting_sample36_top4_20260505_022729_simplified_texts_only.csv True
LORA_LLAMA_EVAL_CSV: /home/harielpadillasanchez/Documentos/TT/TT2/outputs/lora_runs/lora_llama3_feina_repr30_v1/evaluation/lora_test_evaluated.csv True
LORA_MISTRAL_EVAL_CSV: /home/harielpadillasanchez/Documentos/TT/TT2/outputs/lora_runs/lora_mistral_feina_repr30_v1/evaluation/lora_test_evaluated.csv True
FINAL_DIR: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36

In [8]:
sample_ids_df = pd.read_csv(SAMPLE36_IDS_CSV)
sample_ids = set(sample_ids_df["row_id"].tolist())

print("N ids muestra:", len(sample_ids))
print(sorted(list(sample_ids))[:15])

N ids muestra: 36
[550, 571, 885, 1193, 1391, 1399, 1636, 1740, 1742, 1790, 1920, 2027, 2065, 2365, 2449]

In [9]:
prompt_df = pd.read_csv(PROMPTING_SIMPLIFIED_CSV)

print("Shape prompt_df:", prompt_df.shape)
display(prompt_df.head(3))
print(prompt_df.columns.tolist())

Shape prompt_df: (144, 14)

,row_id,prompt_family,owner,model_key,config_label,ruleset,source_text,reference_text,generated_text,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy
0,550,few-shot,hariel,llama3,llama3_cfg_3,R1,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,Sin motivación y sin incentivos no se puede tr...,32.203642,0.744898,0.142857,1.166667,0
1,571,few-shot,hariel,llama3,llama3_cfg_3,R1,En los procesos de importaciones y exportacion...,Clientes y proveedores intervienen en las impo...,"En la importación y exportación, también parti...",44.060676,0.785588,0.272727,0.592593,0
2,885,few-shot,hariel,llama3,llama3_cfg_3,R1,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,El robo de identidad es cuando alguien utiliza...,17.219228,0.852907,0.588235,0.878788,0

['row_id', 'prompt_family', 'owner', 'model_key', 'config_label', 'ruleset', 'source_text', 'reference_text', 'generated_text', 'sari', 'bertscore_f1', 'rougeL_f', 'compression_ratio_eval', 'exact_copy']

In [10]:
prompt_keep_cols = [
    c for c in [
        "row_id",
        "prompt_family",
        "owner",
        "model_key",
        "config_label",
        "ruleset",
        "source_text",
        "reference_text",
        "generated_text",
        "sari",
        "bertscore_f1",
        "rougeL_f",
        "compression_ratio_eval",
        "exact_copy",
    ]
    if c in prompt_df.columns
]

prompt_final_df = prompt_df[prompt_keep_cols].copy()
prompt_final_df["system_family"] = "prompting"
prompt_final_df["system_name"] = (
    prompt_final_df["prompt_family"] + "_" +
    prompt_final_df["owner"] + "_" +
    prompt_final_df["model_key"] + "_" +
    prompt_final_df["config_label"] + "_" +
    prompt_final_df["ruleset"]
)

prompt_final_df = prompt_final_df.sort_values(
    by=["system_name", "row_id"]
).reset_index(drop=True)

print("Shape prompt_final_df:", prompt_final_df.shape)
display(prompt_final_df.head(5))

Shape prompt_final_df: (144, 16)

,row_id,prompt_family,owner,model_key,config_label,ruleset,source_text,reference_text,generated_text,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy,system_family,system_name
0,550,few-shot,hariel,llama3,llama3_cfg_3,R1,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,Sin motivación y sin incentivos no se puede tr...,32.203642,0.744898,0.142857,1.166667,0,prompting,few-shot_hariel_llama3_llama3_cfg_3_R1
1,571,few-shot,hariel,llama3,llama3_cfg_3,R1,En los procesos de importaciones y exportacion...,Clientes y proveedores intervienen en las impo...,"En la importación y exportación, también parti...",44.060676,0.785588,0.272727,0.592593,0,prompting,few-shot_hariel_llama3_llama3_cfg_3_R1
2,885,few-shot,hariel,llama3,llama3_cfg_3,R1,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,El robo de identidad es cuando alguien utiliza...,17.219228,0.852907,0.588235,0.878788,0,prompting,few-shot_hariel_llama3_llama3_cfg_3_R1
3,1193,few-shot,hariel,llama3,llama3_cfg_3,R1,Los sueños de los niños tienen una gran varied...,Los sueños de los niños son variados y van des...,"Los niños soñan con cosas muy diferentes, como...",39.355610,0.837914,0.473684,0.750000,0,prompting,few-shot_hariel_llama3_llama3_cfg_3_R1
4,1391,few-shot,hariel,llama3,llama3_cfg_3,R1,Expresiones como soborno y cohecho se refieren...,Expresiones como soborno y cohecho se refieren...,"Expresiones como ""soborno"" y ""cohecho"" se refi...",39.102538,0.895930,0.585366,1.000000,0,prompting,few-shot_hariel_llama3_llama3_cfg_3_R1

In [11]:
lora_llama_df = pd.read_csv(LORA_LLAMA_EVAL_CSV)

print("Shape lora_llama_df:", lora_llama_df.shape)
display(lora_llama_df.head(3))
print(lora_llama_df.columns.tolist())

Shape lora_llama_df: (238, 30)

,row_id,instruction,generated_text,source_text,reference_text,src_words,pred_words,ref_words,src_sentences,pred_sentences,...,additions_proportion,deletions_proportion,inflesz_pred,inflesz_src,inflesz_delta,rouge1_f,rouge2_f,rougeL_f,bertscore_f1,sbert_similarity
0,92,Reescribe en español el siguiente texto con le...,Muchas personas no tienen el hábito de presupu...,"Muchas personas, más de las que uno pueda imag...",Muchas personas no tienen el hábito de presupu...,35,28,23,1,1,...,0.000000,0.200000,54.235,49.015000,5.220000,0.867925,0.823529,0.867925,0.952885,NaN
1,115,Reescribe en español el siguiente texto con le...,Uno de los problemas que enfrentan las persona...,Uno de los mayores problemas que enfrentan las...,"Uno de los mayores problemas de las personas, ...",50,44,43,1,2,...,0.045455,0.160000,75.810,44.695000,31.115000,0.750000,0.510638,0.750000,0.914103,NaN
2,118,Reescribe en español el siguiente texto con le...,El comportamiento del ingreso marca etapas o c...,El comportamiento del ingreso marca etapas o c...,El comportamiento del ingreso marca etapas o c...,49,47,43,1,2,...,0.063830,0.102041,58.735,39.592143,19.142857,0.828283,0.659794,0.808081,0.923157,NaN

['row_id', 'instruction', 'generated_text', 'source_text', 'reference_text', 'src_words', 'pred_words', 'ref_words', 'src_sentences', 'pred_sentences', 'ref_sentences', 'sari', 'bleu', 'fernandez_huerta_pred', 'fernandez_huerta_src', 'fernandez_huerta_delta', 'compression_ratio_eval', 'sentence_splits', 'levenshtein_similarity', 'exact_copy', 'additions_proportion', 'deletions_proportion', 'inflesz_pred', 'inflesz_src', 'inflesz_delta', 'rouge1_f', 'rouge2_f', 'rougeL_f', 'bertscore_f1', 'sbert_similarity']

In [12]:
lora_mistral_df = pd.read_csv(LORA_MISTRAL_EVAL_CSV)

print("Shape lora_mistral_df:", lora_mistral_df.shape)
display(lora_mistral_df.head(3))
print(lora_mistral_df.columns.tolist())

Shape lora_mistral_df: (238, 30)

,row_id,instruction,generated_text,source_text,reference_text,src_words,pred_words,ref_words,src_sentences,pred_sentences,...,additions_proportion,deletions_proportion,inflesz_pred,inflesz_src,inflesz_delta,rouge1_f,rouge2_f,rougeL_f,bertscore_f1,sbert_similarity
0,92,Reescribe en español el siguiente texto con le...,Muchas personas no tienen el hábito de presupu...,"Muchas personas, más de las que uno pueda imag...",Muchas personas no tienen el hábito de presupu...,35,28,23,1,1,...,0.000000,0.200000,54.235000,49.015000,5.220000,0.867925,0.823529,0.867925,0.952885,NaN
1,115,Reescribe en español el siguiente texto con le...,Uno de los mayores problemas que enfrentan las...,Uno de los mayores problemas que enfrentan las...,"Uno de los mayores problemas de las personas, ...",50,48,43,1,2,...,0.000000,0.040000,71.214167,44.695000,26.519167,0.800000,0.612245,0.800000,0.922216,NaN
2,118,Reescribe en español el siguiente texto con le...,"La primera etapa es la de la educación básica,...",El comportamiento del ingreso marca etapas o c...,El comportamiento del ingreso marca etapas o c...,49,29,43,1,2,...,0.034483,0.428571,76.328103,39.592143,36.735961,0.784810,0.649351,0.607595,0.871772,NaN

['row_id', 'instruction', 'generated_text', 'source_text', 'reference_text', 'src_words', 'pred_words', 'ref_words', 'src_sentences', 'pred_sentences', 'ref_sentences', 'sari', 'bleu', 'fernandez_huerta_pred', 'fernandez_huerta_src', 'fernandez_huerta_delta', 'compression_ratio_eval', 'sentence_splits', 'levenshtein_similarity', 'exact_copy', 'additions_proportion', 'deletions_proportion', 'inflesz_pred', 'inflesz_src', 'inflesz_delta', 'rouge1_f', 'rouge2_f', 'rougeL_f', 'bertscore_f1', 'sbert_similarity']

In [13]:
lora_llama_36 = (
    lora_llama_df[lora_llama_df["row_id"].isin(sample_ids)]
    .copy()
    .sort_values("row_id")
    .reset_index(drop=True)
)

lora_mistral_36 = (
    lora_mistral_df[lora_mistral_df["row_id"].isin(sample_ids)]
    .copy()
    .sort_values("row_id")
    .reset_index(drop=True)
)

print("Shape lora_llama_36:", lora_llama_36.shape)
print("Shape lora_mistral_36:", lora_mistral_36.shape)

Shape lora_llama_36: (36, 30)
Shape lora_mistral_36: (36, 30)

In [14]:
assert len(lora_llama_36) == 36, f"LoRA llama3 no quedo en 36, quedo en {len(lora_llama_36)}"
assert len(lora_mistral_36) == 36, f"LoRA mistral no quedo en 36, quedo en {len(lora_mistral_36)}"

assert set(lora_llama_36["row_id"]) == sample_ids
assert set(lora_mistral_36["row_id"]) == sample_ids

print("OK LoRA filtrado a los mismos 36 ids")

OK LoRA filtrado a los mismos 36 ids

In [15]:
def normalize_lora(df: pd.DataFrame, model_name: str) -> pd.DataFrame:
    out = df.copy()

    rename_map = {}
    if "pred_text" in out.columns and "generated_text" not in out.columns:
        rename_map["pred_text"] = "generated_text"
    if "prediction" in out.columns and "generated_text" not in out.columns:
        rename_map["prediction"] = "generated_text"

    if rename_map:
        out = out.rename(columns=rename_map)

    required = ["row_id", "source_text", "reference_text", "generated_text"]
    missing = [c for c in required if c not in out.columns]
    if missing:
        raise ValueError(f"Faltan columnas en LoRA {model_name}: {missing}")

    keep_cols = [
        c for c in [
            "row_id",
            "source_text",
            "reference_text",
            "generated_text",
            "sari",
            "bertscore_f1",
            "rougeL_f",
            "compression_ratio_eval",
            "exact_copy",
        ]
        if c in out.columns
    ]

    out = out[keep_cols].copy()
    out["prompt_family"] = "fine-tuning"
    out["owner"] = "lora"
    out["model_key"] = model_name
    out["config_label"] = "final_adapter"
    out["ruleset"] = "NA"
    out["system_family"] = "lora"
    out["system_name"] = f"lora_{model_name}"

    ordered_cols = [
        "row_id",
        "prompt_family",
        "owner",
        "model_key",
        "config_label",
        "ruleset",
        "system_family",
        "system_name",
        "source_text",
        "reference_text",
        "generated_text",
        "sari",
        "bertscore_f1",
        "rougeL_f",
        "compression_ratio_eval",
        "exact_copy",
    ]

    ordered_cols = [c for c in ordered_cols if c in out.columns]
    return out[ordered_cols].sort_values("row_id").reset_index(drop=True)

lora_llama_final = normalize_lora(lora_llama_36, "llama3")
lora_mistral_final = normalize_lora(lora_mistral_36, "mistral")

display(lora_llama_final.head(3))
display(lora_mistral_final.head(3))

,row_id,prompt_family,owner,model_key,config_label,ruleset,system_family,system_name,source_text,reference_text,generated_text,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy
0,550,fine-tuning,lora,llama3,final_adapter,NA,lora,lora_llama3,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,"No tiene incentivos ni motivación, dos element...",8.704453,0.859113,0.615385,1.000000,1
1,571,fine-tuning,lora,llama3,final_adapter,NA,lora,lora_llama3,En los procesos de importaciones y exportacion...,Clientes y proveedores intervienen en las impo...,En los procesos de importaciones y exportacion...,17.659459,0.817933,0.346154,0.962963,0
2,885,fine-tuning,lora,llama3,final_adapter,NA,lora,lora_llama3,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,33.659623,0.908836,0.701754,0.606061,0

,row_id,prompt_family,owner,model_key,config_label,ruleset,system_family,system_name,source_text,reference_text,generated_text,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy
0,550,fine-tuning,lora,mistral,final_adapter,NA,lora,lora_mistral,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,"No tiene incentivos ni motivación, dos element...",8.704453,0.859113,0.615385,1.000000,1
1,571,fine-tuning,lora,mistral,final_adapter,NA,lora,lora_mistral,En los procesos de importaciones y exportacion...,Clientes y proveedores intervienen en las impo...,En los procesos de importaciones y exportacion...,29.937673,0.797847,0.285714,0.629630,0
2,885,fine-tuning,lora,mistral,final_adapter,NA,lora,lora_mistral,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,33.659623,0.908836,0.701754,0.606061,0

In [16]:
all_systems_df = pd.concat(
    [
        prompt_final_df,
        lora_llama_final,
        lora_mistral_final,
    ],
    ignore_index=True
)

all_systems_df = all_systems_df.sort_values(
    by=["system_family", "system_name", "row_id"]
).reset_index(drop=True)

print("Shape all_systems_df:", all_systems_df.shape)
display(all_systems_df.head(10))

Shape all_systems_df: (216, 16)

,row_id,prompt_family,owner,model_key,config_label,ruleset,source_text,reference_text,generated_text,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy,system_family,system_name
0,550,fine-tuning,lora,llama3,final_adapter,NA,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,"No tiene incentivos ni motivación, dos element...",8.704453,0.859113,0.615385,1.000000,1,lora,lora_llama3
1,571,fine-tuning,lora,llama3,final_adapter,NA,En los procesos de importaciones y exportacion...,Clientes y proveedores intervienen en las impo...,En los procesos de importaciones y exportacion...,17.659459,0.817933,0.346154,0.962963,0,lora,lora_llama3
2,885,fine-tuning,lora,llama3,final_adapter,NA,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,33.659623,0.908836,0.701754,0.606061,0,lora,lora_llama3
3,1193,fine-tuning,lora,llama3,final_adapter,NA,Los sueños de los niños tienen una gran varied...,Los sueños de los niños son variados y van des...,Los sueños de los niños tienen una gran variedad.,33.402881,0.804006,0.451613,0.450000,0,lora,lora_llama3
4,1391,fine-tuning,lora,llama3,final_adapter,NA,Expresiones como soborno y cohecho se refieren...,Expresiones como soborno y cohecho se refieren...,Expresiones como soborno y cohecho se refieren...,21.647674,0.958191,0.761905,1.000000,1,lora,lora_llama3
5,1399,fine-tuning,lora,llama3,final_adapter,NA,"DIRECCIÓN DE PRESUPUESTO (DIPRES): ""formula y ...",DIRECCIÓN DE PRESUPUESTO: formula y lleva el c...,La Dirección de Presupuesto formula y lleva el...,86.031746,0.800695,0.965517,1.000000,0,lora,lora_llama3
6,1636,fine-tuning,lora,llama3,final_adapter,NA,Interés compuesto: Es la suma del capital y el...,El interés compuesto es la suma del capital y ...,El interés compuesto es la suma del capital y ...,71.419187,0.984089,0.937500,0.800000,0,lora,lora_llama3
7,1740,fine-tuning,lora,llama3,final_adapter,NA,La producción en un país se realiza mediante l...,A través de los factores de producción se real...,La producción en un país se realiza mediante l...,54.436121,0.873674,0.461538,0.730769,0,lora,lora_llama3
8,1742,fine-tuning,lora,llama3,final_adapter,NA,A pesar de que algunos critican al intermediar...,Aunque algunas personas critican al intermedia...,"Algunos critican al intermediario, pero se nec...",37.500000,0.901409,0.642857,0.812500,0,lora,lora_llama3
9,1790,fine-tuning,lora,llama3,final_adapter,NA,El impuesto a los réditos es también un buen i...,El impuesto a las utilidades también es un bue...,El impuesto a los réditos es un buen instrumen...,43.506494,0.946151,0.782609,0.954545,0,lora,lora_llama3

In [17]:
summary_rows = []

for system_name, g in all_systems_df.groupby("system_name"):
    row = {
        "system_name": system_name,
        "system_family": g["system_family"].iloc[0],
        "n_rows": len(g),
    }

    for metric in ["sari", "bertscore_f1", "rougeL_f", "compression_ratio_eval", "exact_copy"]:
        if metric in g.columns:
            row[metric] = g[metric].mean()

    if "sari" in row and "bertscore_f1" in row:
        row["leader_score"] = 0.6 * row["sari"] + 0.4 * (row["bertscore_f1"] * 100.0)

    summary_rows.append(row)

final_summary_df = pd.DataFrame(summary_rows).sort_values(
    by=["leader_score", "sari", "bertscore_f1"],
    ascending=False
).reset_index(drop=True)

display(final_summary_df)

,system_name,system_family,n_rows,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy,leader_score
0,lora_llama3,lora,36,44.218183,0.895692,0.686885,0.835316,0.138889,62.358570
1,lora_mistral,lora,36,39.990620,0.891969,0.679365,0.868639,0.194444,59.673112
2,few-shot_hariel_llama3_llama3_cfg_3_R1,prompting,36,36.161632,0.814534,0.402859,1.040341,0.000000,54.278349
3,few-shot_nancy_llama3_llama3_cfg_2_R2,prompting,36,35.025034,0.818844,0.389381,0.923332,0.000000,53.768799
4,zero-shot_hariel_llama3_hariel_llama3_cfg_1_R0,prompting,36,34.580136,0.813240,0.387453,0.763318,0.000000,53.277701
5,zero-shot_nancy_mistral_nancy_mistral_cfg_2_R4,prompting,36,36.577888,0.773919,0.380849,1.261758,0.000000,52.903505

In [18]:
prompt_only_path = FINAL_DIR / "01_prompting_top4_simplificaciones.csv"
lora_llama_path = FINAL_DIR / "02_lora_llama3_sample36.csv"
lora_mistral_path = FINAL_DIR / "03_lora_mistral_sample36.csv"
all_systems_path = FINAL_DIR / "04_todos_los_sistemas_sample36.csv"
summary_path = FINAL_DIR / "05_resumen_comparacion_sample36.csv"
ids_path = FINAL_DIR / "00_ids_sample36.csv"

sample_ids_df.to_csv(ids_path, index=False, encoding="utf-8-sig")
prompt_final_df.to_csv(prompt_only_path, index=False, encoding="utf-8-sig")
lora_llama_final.to_csv(lora_llama_path, index=False, encoding="utf-8-sig")
lora_mistral_final.to_csv(lora_mistral_path, index=False, encoding="utf-8-sig")
all_systems_df.to_csv(all_systems_path, index=False, encoding="utf-8-sig")
final_summary_df.to_csv(summary_path, index=False, encoding="utf-8-sig")

print("Guardado:", ids_path)
print("Guardado:", prompt_only_path)
print("Guardado:", lora_llama_path)
print("Guardado:", lora_mistral_path)
print("Guardado:", all_systems_path)
print("Guardado:", summary_path)

Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/00_ids_sample36.csv
Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/01_prompting_top4_simplificaciones.csv
Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/02_lora_llama3_sample36.csv
Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/03_lora_mistral_sample36.csv
Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/04_todos_los_sistemas_sample36.csv
Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/05_resumen_comparacion_sample36.csv

In [19]:
rubrica_df = all_systems_df.pivot_table(
    index=["row_id", "source_text", "reference_text"],
    columns="system_name",
    values="generated_text",
    aggfunc="first"
).reset_index()

rubrica_path = FINAL_DIR / "06_para_rubrica_sample36_wide.csv"
rubrica_df.to_csv(rubrica_path, index=False, encoding="utf-8-sig")

print("Guardado:", rubrica_path)
display(rubrica_df.head(3))

Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/06_para_rubrica_sample36_wide.csv

system_name,row_id,source_text,reference_text,few-shot_hariel_llama3_llama3_cfg_3_R1,few-shot_nancy_llama3_llama3_cfg_2_R2,lora_llama3,lora_mistral,zero-shot_hariel_llama3_hariel_llama3_cfg_1_R0,zero-shot_nancy_mistral_nancy_mistral_cfg_2_R4
0,550,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,Sin motivación y sin incentivos no se puede tr...,No tiene motivación para trabajar bien y ganar...,"No tiene incentivos ni motivación, dos element...","No tiene incentivos ni motivación, dos element...","No tiene motivos ni ganas, dos cosas important...","No tiene incentivos ni motivation, que son nec..."
1,571,En los procesos de importaciones y exportacion...,Clientes y proveedores intervienen en las impo...,"En la importación y exportación, también parti...","En la importación y exportación, están involuc...",En los procesos de importaciones y exportacion...,En los procesos de importaciones y exportacion...,"Involucran instituciones del Estado y bancos, ...",En importaciones y exportaciones intervenen ad...
2,885,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,El robo de identidad es cuando alguien utiliza...,El robo de identidad es cuando alguien utiliza...,El robo de identidad ocurre cuando su informac...,El robo de identidad ocurre cuando su informac...,El robo de identidad es cuando alguien usa su ...,Robo de identidad: se utiliza tu información p...

In [20]:
print("Resumen final")
print("-" * 50)
print("N ids muestra:", len(sample_ids))
print("Prompting filas:", len(prompt_final_df))
print("LoRA llama3 filas:", len(lora_llama_final))
print("LoRA mistral filas:", len(lora_mistral_final))
print("Total consolidado:", len(all_systems_df))

print("\nTop sistemas:")
display(final_summary_df.head(10))

Resumen final
--------------------------------------------------
N ids muestra: 36
Prompting filas: 144
LoRA llama3 filas: 36
LoRA mistral filas: 36
Total consolidado: 216

Top sistemas:

,system_name,system_family,n_rows,sari,bertscore_f1,rougeL_f,compression_ratio_eval,exact_copy,leader_score
0,lora_llama3,lora,36,44.218183,0.895692,0.686885,0.835316,0.138889,62.358570
1,lora_mistral,lora,36,39.990620,0.891969,0.679365,0.868639,0.194444,59.673112
2,few-shot_hariel_llama3_llama3_cfg_3_R1,prompting,36,36.161632,0.814534,0.402859,1.040341,0.000000,54.278349
3,few-shot_nancy_llama3_llama3_cfg_2_R2,prompting,36,35.025034,0.818844,0.389381,0.923332,0.000000,53.768799
4,zero-shot_hariel_llama3_hariel_llama3_cfg_1_R0,prompting,36,34.580136,0.813240,0.387453,0.763318,0.000000,53.277701
5,zero-shot_nancy_mistral_nancy_mistral_cfg_2_R4,prompting,36,36.577888,0.773919,0.380849,1.261758,0.000000,52.903505

In [21]:
rubrica_long_df = all_systems_df.copy()

# ordenar para revisión más cómoda
rubrica_long_df = rubrica_long_df.sort_values(
    by=["row_id", "system_name"]
).reset_index(drop=True)

# columnas base que sí conviene mostrar al evaluador
base_cols = [
    c for c in [
        "row_id",
        "system_name",
        "system_family",
        "source_text",
        "reference_text",
        "generated_text",
    ]
    if c in rubrica_long_df.columns
]

rubrica_long_df = rubrica_long_df[base_cols].copy()

# pesos de la rúbrica
WEIGHTS = {
    "fidelidad_semantica": 30,
    "comprension_claridad": 25,
    "fluidez_correccion": 15,
    "adecuacion_publico_tono": 10,
    "lexico_sintaxis": 10,
    "estructura_presentacion": 5,
    "manejo_numeros_datos": 5,
}

# descripciones cortas para que la persona evaluadora no tenga que abrir otro archivo
rubrica_long_df["criterio_fidelidad"] = "Conserva ideas centrales, datos clave y relaciones del original."
rubrica_long_df["criterio_comprension"] = "Se entiende al primer vistazo, sin ambigüedades importantes."
rubrica_long_df["criterio_fluidez"] = "Suena natural, con buena gramática y cohesión."
rubrica_long_df["criterio_tono"] = "Tono cercano, educativo, neutral y apropiado para el público."
rubrica_long_df["criterio_lexico"] = "Palabras comunes, oraciones cortas, sin tecnicismos innecesarios."
rubrica_long_df["criterio_estructura"] = "Orden lógico, párrafos manejables, presentación clara."
rubrica_long_df["criterio_numeros"] = "Cifras con contexto y simplificadas correctamente."

# pesos visibles
rubrica_long_df["peso_fidelidad"] = WEIGHTS["fidelidad_semantica"]
rubrica_long_df["peso_comprension"] = WEIGHTS["comprension_claridad"]
rubrica_long_df["peso_fluidez"] = WEIGHTS["fluidez_correccion"]
rubrica_long_df["peso_tono"] = WEIGHTS["adecuacion_publico_tono"]
rubrica_long_df["peso_lexico"] = WEIGHTS["lexico_sintaxis"]
rubrica_long_df["peso_estructura"] = WEIGHTS["estructura_presentacion"]
rubrica_long_df["peso_numeros"] = WEIGHTS["manejo_numeros_datos"]

# columnas vacías para capturar la calificación (1 a 5)
rubrica_long_df["score_fidelidad"] = ""
rubrica_long_df["score_comprension"] = ""
rubrica_long_df["score_fluidez"] = ""
rubrica_long_df["score_tono"] = ""
rubrica_long_df["score_lexico"] = ""
rubrica_long_df["score_estructura"] = ""
rubrica_long_df["score_numeros"] = ""

# columnas de apoyo para captura rápida
rubrica_long_df["escala_recordatorio"] = "1, 2, 3, 4 o 5"
rubrica_long_df["comentarios_evaluador"] = ""
rubrica_long_df["evaluador"] = ""
rubrica_long_df["fecha_evaluacion"] = ""

# puntajes ponderados vacíos
rubrica_long_df["weighted_fidelidad"] = ""
rubrica_long_df["weighted_comprension"] = ""
rubrica_long_df["weighted_fluidez"] = ""
rubrica_long_df["weighted_tono"] = ""
rubrica_long_df["weighted_lexico"] = ""
rubrica_long_df["weighted_estructura"] = ""
rubrica_long_df["weighted_numeros"] = ""
rubrica_long_df["score_total_100"] = ""

# reordenar columnas
ordered_cols = [
    "row_id",
    "system_name",
    "system_family",
    "source_text",
    "reference_text",
    "generated_text",

    "criterio_fidelidad",
    "peso_fidelidad",
    "score_fidelidad",
    "weighted_fidelidad",

    "criterio_comprension",
    "peso_comprension",
    "score_comprension",
    "weighted_comprension",

    "criterio_fluidez",
    "peso_fluidez",
    "score_fluidez",
    "weighted_fluidez",

    "criterio_tono",
    "peso_tono",
    "score_tono",
    "weighted_tono",

    "criterio_lexico",
    "peso_lexico",
    "score_lexico",
    "weighted_lexico",

    "criterio_estructura",
    "peso_estructura",
    "score_estructura",
    "weighted_estructura",

    "criterio_numeros",
    "peso_numeros",
    "score_numeros",
    "weighted_numeros",

    "score_total_100",
    "escala_recordatorio",
    "comentarios_evaluador",
    "evaluador",
    "fecha_evaluacion",
]

ordered_cols = [c for c in ordered_cols if c in rubrica_long_df.columns]
rubrica_long_df = rubrica_long_df[ordered_cols].copy()

rubrica_long_path = FINAL_DIR / "07_para_rubrica_sample36_long.csv"
rubrica_long_df.to_csv(rubrica_long_path, index=False, encoding="utf-8-sig")

print("Guardado:", rubrica_long_path)
print("Filas:", len(rubrica_long_df))
display(rubrica_long_df.head(6))

Guardado: /home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/07_para_rubrica_sample36_long.csv
Filas: 216

,row_id,system_name,system_family,source_text,reference_text,generated_text,criterio_fidelidad,peso_fidelidad,score_fidelidad,weighted_fidelidad,...,weighted_estructura,criterio_numeros,peso_numeros,score_numeros,weighted_numeros,score_total_100,escala_recordatorio,comentarios_evaluador,evaluador,fecha_evaluacion
0,550,few-shot_hariel_llama3_llama3_cfg_3_R1,prompting,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,Sin motivación y sin incentivos no se puede tr...,"Conserva ideas centrales, datos clave y relaci...",30,,,...,,Cifras con contexto y simplificadas correctame...,5,,,,"1, 2, 3, 4 o 5",,,
1,550,few-shot_nancy_llama3_llama3_cfg_2_R2,prompting,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,No tiene motivación para trabajar bien y ganar...,"Conserva ideas centrales, datos clave y relaci...",30,,,...,,Cifras con contexto y simplificadas correctame...,5,,,,"1, 2, 3, 4 o 5",,,
2,550,lora_llama3,lora,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,"No tiene incentivos ni motivación, dos element...","Conserva ideas centrales, datos clave y relaci...",30,,,...,,Cifras con contexto y simplificadas correctame...,5,,,,"1, 2, 3, 4 o 5",,,
3,550,lora_mistral,lora,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,"No tiene incentivos ni motivación, dos element...","Conserva ideas centrales, datos clave y relaci...",30,,,...,,Cifras con contexto y simplificadas correctame...,5,,,,"1, 2, 3, 4 o 5",,,
4,550,zero-shot_hariel_llama3_hariel_llama3_cfg_1_R0,prompting,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,"No tiene motivos ni ganas, dos cosas important...","Conserva ideas centrales, datos clave y relaci...",30,,,...,,Cifras con contexto y simplificadas correctame...,5,,,,"1, 2, 3, 4 o 5",,,
5,550,zero-shot_nancy_mistral_nancy_mistral_cfg_2_R4,prompting,"No tiene incentivos ni motivación, dos element...",No tiene sentido ni motivación. Estos elemento...,"No tiene incentivos ni motivation, que son nec...","Conserva ideas centrales, datos clave y relaci...",30,,,...,,Cifras con contexto y simplificadas correctame...,5,,,,"1, 2, 3, 4 o 5",,,

In [22]:
print("Escala de evaluación manual:")
print("5 = Cumple bien")
print("3 = Cumple a medias")
print("1 = No cumple")
print("\nArchivo para llenar:")
print(FINAL_DIR / "07_para_rubrica_sample36_long.csv")

Escala de evaluación manual:
5 = Cumple bien
3 = Cumple a medias
1 = No cumple

Archivo para llenar:
/home/harielpadillasanchez/Documentos/TT/TT2/FINAL_COMPARACION_36/07_para_rubrica_sample36_long.csv